In [23]:
import numpy as np

In [17]:
a=np.array([1,2,2], dtype="int32")
print(a)
a

[1 2 2]


array([1, 2, 2])

In [9]:
b=np.array([[1,2,3],[4,5,6]])
b.ndim

2

In [12]:
a.shape


(3,)

In [13]:
b.shape

(2, 3)

In [16]:
a.dtype

dtype('int32')

In [18]:
a.itemsize

4

In [19]:
#get totalsize
a.nbytes

12

In [20]:
#num of elements
a.size

3

## Accessing elements

In [31]:
a=np.array([[1,2,3,4,6],[5,6,7,8,6]])
print(a)

[[1 2 3 4 6]
 [5 6 7 8 6]]


In [32]:
#(r,c)
a[0,:]

array([1, 2, 3, 4, 6])

In [33]:
a[:,1]

array([2, 6])

In [34]:
#[startindex, endindex, step]
a[0,1:-1:2]

array([2, 4])

In [35]:
a[1,3]=20
a

array([[ 1,  2,  3,  4,  6],
       [ 5,  6,  7, 20,  6]])

In [36]:
a[:,2]=[12,13]
a

array([[ 1,  2, 12,  4,  6],
       [ 5,  6, 13, 20,  6]])

In [38]:
#3d dimension
b=np.array([[[1,2],[3,4]],[[4,5],[6,7]]])
print(b)

[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]


In [41]:
# 0 is above matrix and 1 is the below one
b[1,:,1]

array([5, 7])

In [43]:
b[:,1,:]=[[5,6],[8,9]]
print(b)

[[[1 2]
  [5 6]]

 [[4 5]
  [8 9]]]


## Initializing Types of Array

In [45]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
np.ones((4,2,2), dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [48]:
#any other num
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [49]:
np.full_like(a,9)

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [50]:
a

array([[ 1,  2, 12,  4,  6],
       [ 5,  6, 13, 20,  6]])

In [52]:
np.random.rand(4,3)

array([[0.94567771, 0.69072573, 0.24414291],
       [0.38082669, 0.14228795, 0.70518881],
       [0.61349283, 0.47432606, 0.36469343],
       [0.28514761, 0.48145775, 0.7966266 ]])

In [55]:
np.random.randint(-4,10, size=(3,3))

array([[ 2,  1,  6],
       [ 8,  0,  7],
       [ 2, -2,  0]])

In [56]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Numpy Dimension

Axis 0 is TOP to Bottom and Axis 1 is Left to right. So basically axis 0 is col and axs 1 is row 
for2D array. 
In 1D Array there is only 1 axis hence Axis 0 is L to R. Therefore Axis 0 is Row

In [59]:
#repeat array
arr=np.array([[1,23,3]])
r1=np.repeat(arr,5,axis=0)
print(r1)

[[ 1 23  3]
 [ 1 23  3]
 [ 1 23  3]
 [ 1 23  3]
 [ 1 23  3]]


In [60]:
#repeat array
arr=np.array([1,23,3])
r1=np.repeat(arr,5,axis=0)
print(r1)

[ 1  1  1  1  1 23 23 23 23 23  3  3  3  3  3]


In [63]:
#copies z matrix in output
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1]=z
print(output)

output[:,:]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


ValueError: could not broadcast input array from shape (3,3) into shape (5,5)

In [67]:
a=np.array([1,2,33])
b=a.copy()
b[0]=100
print(a)
print(b)

[ 1  2 33]
[100   2  33]


In [68]:
a=np.array([1,2,33])
b=a
b[0]=100
print(a)
print(b)

[100   2  33]
[100   2  33]


## Linear Algebra

In [72]:
a=np.ones((3,2))
print(a)

b=np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [73]:
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [75]:
#determinant
c=np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

## Reorganizing Arrays

In [77]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
before.shape

after=before.reshape(4,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [78]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [79]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.hstack([v1,v2,v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])

In [80]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [82]:
a=np.array([12,3,4,6,5,7])
a[[0,-1]]

array([12,  7])